AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  VpcId:
    Description: The ID of the VPC where the services will be created.
    Type: String
  SubnetId:
    Description: The ID of the subnet where the instance will be created.
    Type: String
  MgmtSourceIp:
    Description: The IP address (in CIDR notation) that will be allowed to manage the instance.
    Type: String
  UserSourceIp:
    Description: The IP address (in CIDR notation) that will be allowed to use the instance.
    Type: String
  ImageId:
    Description: The ID of the AMI to use for the instance.
    Type: String
    Default: ami-041c914bb6988afbd
  KeyPairName:
    Description: The name of the key pair to use for the instance.
    Type: String
    Default: ec2_keypair

Resources:
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH and ping access from specific IP addresses
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref MgmtSourceIp
        - IpProtocol: icmp
          FromPort: -1
          ToPort: -1
          CidrIp: !Ref UserSourceIp
      GroupName: !Sub "${AWS::StackName}-SecurityGroup"
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-SecurityGroup"
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AWS::AccountId}-${AWS::StackName}-backup"
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-Backup"

  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref EC2Role

  EC2Role:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${AWS::StackName}-EC2Role"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: !Sub "${AWS::StackName}-S3AccessPolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "s3:GetObject"
                  - "s3:PutObject"
                Resource: !Sub "arn:aws:s3:::${S3Bucket}/*"

  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t4g.small
      ImageId: !Ref ImageId
      KeyName: !Ref KeyPairName
      SecurityGroupIds:
        - !Ref SecurityGroup
      SubnetId: !Ref SubnetId
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-Instance"
      IamInstanceProfile: !Ref InstanceProfile

Outputs:
  SecurityGroupId:
    Description: The ID of the created security group
    Value: !Ref SecurityGroup
