version: '3.8'
services:
  devcontainer:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        BASE_IMAGE: "${DOCKER_LOCAL_REGISTRY}/development"
    volumes:
      # Mount from the root to access .git in the vscode running in the container.
      - ../../..:/workspace:cached
    command: sleep infinity
